/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Version
         * @description Vertical slice: return API version + git sha
         */
        get: operations["get_version_api_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description List sessions with pagination.
         */
        get: operations["list_sessions_api_v1_sessions__get"];
        put?: never;
        /**
         * Create Session
         * @description Create a new research session.
         */
        post: operations["create_session_api_v1_sessions__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description Retrieve a single session by ID.
         */
        get: operations["get_session_api_v1_sessions__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description Delete a session and its workspace directory.
         */
        delete: operations["delete_session_api_v1_sessions__session_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Session
         * @description Update a session's mutable fields (name, description, status).
         */
        patch: operations["update_session_api_v1_sessions__session_id__patch"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Index Workspace
         * @description Trigger indexing for a workspace.
         */
        post: operations["index_workspace_api_v1_workspaces__workspace_id__index_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/index/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Index Status
         * @description Check the indexing status of a workspace.
         */
        get: operations["get_index_status_api_v1_workspaces__workspace_id__index_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/content/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Content
         * @description List all content items for a session with pagination.
         */
        get: operations["list_content_api_v1_sessions__session_id__content__get"];
        put?: never;
        /**
         * Add Content
         * @description Add content to a session.
         *
         *     Supports multiple content types:
         *     - text: Plain text content (source contains the text)
         *     - file_upload: Upload a file (use the file parameter)
         *     - url: Fetch content from URL (source contains the URL)
         *     - git_repo: Clone a git repository (source contains the repo URL)
         */
        post: operations["add_content_api_v1_sessions__session_id__content__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/content/{content_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Content
         * @description Get a single content item by ID.
         */
        get: operations["get_content_api_v1_sessions__session_id__content__content_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Content
         * @description Delete a content item and its storage files.
         */
        delete: operations["delete_content_api_v1_sessions__session_id__content__content_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/content/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch Add Content
         * @description Add multiple URLs as content items to a session.
         *
         *     Supports batch adding of URLs with automatic duplicate detection.
         *     Duplicates are identified by matching source_ref (URL) against existing
         *     content in the session, as well as within the batch itself.
         *
         *     Args:
         *         session_id: Target session ID.
         *         request: Batch add request containing list of URLs (1-500).
         *
         *     Returns:
         *         BatchContentResponse with per-item results and summary counts.
         */
        post: operations["batch_add_content_api_v1_sessions__session_id__content_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/extract-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Links
         * @description Extract and categorize links from a web page.
         *
         *     Fetches the specified URL and extracts all links, categorizing them by
         *     their source element (main content, navigation, sidebar, footer, other).
         *
         *     Args:
         *         request: Contains the URL to extract links from and options.
         *
         *     Returns:
         *         ExtractedLinksResponse with categorized links and metadata.
         *
         *     Raises:
         *         HTTPException: 400 if URL is invalid or extraction fails.
         */
        post: operations["extract_links_api_v1_content_extract_links_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Audit Logs
         * @description Retrieve audit logs for a session.
         */
        get: operations["get_audit_logs_api_v1_sessions__session_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Chat Messages
         * @description List all chat messages for a session with pagination.
         */
        get: operations["list_chat_messages_api_v1_sessions__session_id__chat_get"];
        put?: never;
        /**
         * Send Chat Message
         * @description Send a new chat message and get a stream URL for the response.
         *
         *     Creates both a user message and a placeholder assistant message.
         *     The assistant message will be populated via the SSE stream endpoint.
         *
         *     The session must be indexed before chat is available.
         */
        post: operations["send_chat_message_api_v1_sessions__session_id__chat_post"];
        /**
         * Clear Chat History
         * @description Clear all chat messages for a session.
         */
        delete: operations["clear_chat_history_api_v1_sessions__session_id__chat_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/chat/stream/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Chat Response
         * @description Stream the AI response for a chat message using Server-Sent Events.
         *
         *     Invokes claude-mpm subprocess to generate response and streams
         *     output line-by-line to the client.
         *
         *     SSE Event Types:
         *     - start: {"message_id": "...", "status": "streaming"}
         *     - chunk: {"content": "line of text"}
         *     - complete: {"message_id": "...", "status": "completed", ...}
         *     - error: {"message_id": "...", "status": "error", "error": "..."}
         *     - heartbeat: {"timestamp": "ISO8601"} (every 15 seconds)
         */
        get: operations["stream_chat_response_api_v1_sessions__session_id__chat_stream__message_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/chat/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chat Message
         * @description Get a single chat message by ID.
         */
        get: operations["get_chat_message_api_v1_sessions__session_id__chat__message_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Chat Message
         * @description Delete a chat message.
         */
        delete: operations["delete_chat_message_api_v1_sessions__session_id__chat__message_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/chat/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export full chat history
         * @description Generate and download full chat history in specified format (PDF or Markdown)
         */
        post: operations["export_chat_history_api_v1_sessions__session_id__chat_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/chat/{message_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export single Q/A pair
         * @description Generate and download a specific question/answer pair
         */
        post: operations["export_single_message_api_v1_sessions__session_id__chat__message_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Health Check
         * @description Health check under the /api/v1 prefix.
         */
        get: operations["api_health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuditLogListResponse
         * @description Paginated list of audit log entries.
         */
        AuditLogListResponse: {
            /** Logs */
            logs: components["schemas"]["AuditLogResponse"][];
            /** Count */
            count: number;
        };
        /**
         * AuditLogResponse
         * @description Single audit log entry returned by the API.
         */
        AuditLogResponse: {
            /** Id */
            id: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Session Id */
            session_id: string;
            /** Action */
            action: string;
            /** Query */
            query?: string | null;
            /** Result Count */
            result_count?: number | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Status */
            status: string;
            /** Error */
            error?: string | null;
            /** Metadata Json */
            metadata_json?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * BatchAddContentRequest
         * @description Request body for POST /api/v1/sessions/{session_id}/content/batch.
         */
        BatchAddContentRequest: {
            /**
             * Urls
             * @description List of URLs to add (1-500)
             */
            urls: components["schemas"]["BatchUrlItem"][];
            /**
             * Source Url
             * @description Source URL where links were extracted from
             */
            source_url?: string | null;
        };
        /**
         * BatchContentItemResponse
         * @description Result for a single URL in batch add response.
         */
        BatchContentItemResponse: {
            /**
             * Content Id
             * @description Content ID if successfully created
             */
            content_id?: string | null;
            /**
             * Url
             * @description The URL that was processed
             */
            url: string;
            /**
             * Status
             * @description Processing status
             * @enum {string}
             */
            status: "success" | "error" | "duplicate";
            /**
             * Title
             * @description Content title
             */
            title?: string | null;
            /**
             * Error
             * @description Error message if failed
             */
            error?: string | null;
        };
        /**
         * BatchContentResponse
         * @description Response for POST /api/v1/sessions/{session_id}/content/batch.
         */
        BatchContentResponse: {
            /**
             * Session Id
             * @description Session ID
             */
            session_id: string;
            /**
             * Total Count
             * @description Total URLs submitted
             */
            total_count: number;
            /**
             * Success Count
             * @description Number of successful additions
             */
            success_count: number;
            /**
             * Error Count
             * @description Number of failed additions
             */
            error_count: number;
            /**
             * Duplicate Count
             * @description Number of duplicate URLs
             */
            duplicate_count: number;
            /**
             * Items
             * @description Per-URL results
             */
            items: components["schemas"]["BatchContentItemResponse"][];
        };
        /**
         * BatchUrlItem
         * @description Single URL item within a batch add content request.
         */
        BatchUrlItem: {
            /**
             * Url
             * Format: uri
             * @description URL to add as content
             */
            url: string;
            /**
             * Title
             * @description Optional title override
             */
            title?: string | null;
        };
        /** Body_add_content_api_v1_sessions__session_id__content__post */
        Body_add_content_api_v1_sessions__session_id__content__post: {
            /**
             * Content Type
             * @description Content type: text, file_upload, url, git_repo
             */
            content_type: string;
            /**
             * Title
             * @description Content title
             */
            title?: string | null;
            /**
             * Source
             * @description Source reference (URL, text)
             */
            source?: string | null;
            /**
             * Metadata
             * @description JSON string of additional metadata
             */
            metadata?: string | null;
            /**
             * File
             * @description File to upload (for file_upload type)
             */
            file?: string | null;
        };
        /**
         * CategorizedLinksSchema
         * @description Links grouped by page section/category.
         */
        CategorizedLinksSchema: {
            /**
             * Main Content
             * @description Links from main content area
             */
            main_content?: components["schemas"]["ExtractedLinkSchema"][];
            /**
             * Navigation
             * @description Links from navigation elements
             */
            navigation?: components["schemas"]["ExtractedLinkSchema"][];
            /**
             * Sidebar
             * @description Links from sidebar areas
             */
            sidebar?: components["schemas"]["ExtractedLinkSchema"][];
            /**
             * Footer
             * @description Links from footer area
             */
            footer?: components["schemas"]["ExtractedLinkSchema"][];
            /**
             * Other
             * @description Links from other/unclassified areas
             */
            other?: components["schemas"]["ExtractedLinkSchema"][];
        };
        /**
         * ChatExportFormat
         * @description Supported export formats for chat history.
         * @enum {string}
         */
        ChatExportFormat: "pdf" | "markdown";
        /**
         * ChatExportRequest
         * @description Request body for chat export endpoints.
         * @example {
         *       "format": "pdf",
         *       "include_metadata": true,
         *       "include_timestamps": true
         *     }
         */
        ChatExportRequest: {
            format: components["schemas"]["ChatExportFormat"];
            /**
             * Include Metadata
             * @default true
             */
            include_metadata: boolean;
            /**
             * Include Timestamps
             * @default true
             */
            include_timestamps: boolean;
        };
        /**
         * ChatMessageListResponse
         * @description Paginated list of chat messages.
         */
        ChatMessageListResponse: {
            /** Messages */
            messages: components["schemas"]["ChatMessageResponse"][];
            /** Count */
            count: number;
        };
        /**
         * ChatMessageResponse
         * @description Single chat message returned by the API.
         */
        ChatMessageResponse: {
            /** Message Id */
            message_id: string;
            /** Session Id */
            session_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "streaming" | "completed" | "error";
            /** Error Message */
            error_message?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at?: string | null;
            /** Token Count */
            token_count?: number | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Metadata Json */
            metadata_json?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ChatMessageWithStreamUrlResponse
         * @description Chat message response with stream URL for SSE connection.
         */
        ChatMessageWithStreamUrlResponse: {
            /** Message Id */
            message_id: string;
            /** Session Id */
            session_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "streaming" | "completed" | "error";
            /** Error Message */
            error_message?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at?: string | null;
            /** Token Count */
            token_count?: number | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Metadata Json */
            metadata_json?: {
                [key: string]: unknown;
            } | null;
            /** Stream Url */
            stream_url?: string | null;
        };
        /**
         * ContentItemResponse
         * @description Single content item returned by the API.
         */
        ContentItemResponse: {
            /** Content Id */
            content_id: string;
            /** Session Id */
            session_id: string;
            /** Content Type */
            content_type: string;
            /** Title */
            title: string;
            /** Source Ref */
            source_ref?: string | null;
            /** Storage Path */
            storage_path?: string | null;
            /** Status */
            status: string;
            /** Error Message */
            error_message?: string | null;
            /** Size Bytes */
            size_bytes?: number | null;
            /** Mime Type */
            mime_type?: string | null;
            /** Metadata Json */
            metadata_json?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ContentListResponse
         * @description Paginated list of content items.
         */
        ContentListResponse: {
            /** Items */
            items: components["schemas"]["ContentItemResponse"][];
            /** Count */
            count: number;
        };
        /**
         * CreateSessionRequest
         * @description Body for POST /api/v1/sessions.
         */
        CreateSessionRequest: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /**
         * ExtractLinksRequest
         * @description Request body for POST /api/v1/sessions/{session_id}/content/extract-links.
         */
        ExtractLinksRequest: {
            /**
             * Url
             * Format: uri
             * @description URL to extract links from
             */
            url: string;
            /**
             * Include External
             * @description Whether to include external links
             * @default true
             */
            include_external: boolean;
        };
        /**
         * ExtractedLinkSchema
         * @description Single extracted link from a page.
         */
        ExtractedLinkSchema: {
            /**
             * Url
             * @description The extracted link URL
             */
            url: string;
            /**
             * Text
             * @description Link text/anchor text
             */
            text?: string | null;
            /**
             * Is External
             * @description Whether link points to external domain
             */
            is_external: boolean;
            /**
             * Source Element
             * @description HTML element type (a, img, etc.)
             */
            source_element?: string | null;
        };
        /**
         * ExtractedLinksResponse
         * @description Response for POST /api/v1/sessions/{session_id}/content/extract-links.
         */
        ExtractedLinksResponse: {
            /**
             * Source Url
             * @description URL that was analyzed
             */
            source_url: string;
            /**
             * Page Title
             * @description Title of the page
             */
            page_title?: string | null;
            /**
             * Extracted At
             * Format: date-time
             * @description Timestamp of extraction
             */
            extracted_at: string;
            /**
             * Link Count
             * @description Total number of links extracted
             */
            link_count: number;
            /** @description Links organized by page section */
            categories: components["schemas"]["CategorizedLinksSchema"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IndexResultResponse
         * @description Response for POST /api/v1/workspaces/{workspace_id}/index.
         */
        IndexResultResponse: {
            /** Workspace Id */
            workspace_id: string;
            /** Success */
            success: boolean;
            /** Status */
            status: string;
            /** Elapsed Seconds */
            elapsed_seconds: number;
            /** Stdout */
            stdout?: string | null;
            /** Stderr */
            stderr?: string | null;
        };
        /**
         * IndexStatusResponse
         * @description Response for GET /api/v1/workspaces/{workspace_id}/index/status.
         */
        IndexStatusResponse: {
            /** Workspace Id */
            workspace_id: string;
            /** Is Indexed */
            is_indexed: boolean;
            /** Status */
            status: string;
            /** Message */
            message: string;
        };
        /**
         * IndexWorkspaceRequest
         * @description Body for POST /api/v1/workspaces/{workspace_id}/index.
         */
        IndexWorkspaceRequest: {
            /**
             * Force
             * @description Force re-index from scratch
             * @default true
             */
            force: boolean;
            /**
             * Timeout
             * @description Custom timeout in seconds (10-600)
             */
            timeout?: number | null;
        };
        /**
         * SendChatMessageRequest
         * @description Body for POST /api/v1/sessions/{session_id}/chat.
         */
        SendChatMessageRequest: {
            /** Content */
            content: string;
        };
        /**
         * SessionListResponse
         * @description Paginated list of sessions.
         */
        SessionListResponse: {
            /** Sessions */
            sessions: components["schemas"]["SessionResponse"][];
            /** Count */
            count: number;
        };
        /**
         * SessionResponse
         * @description Single session returned by the API.
         */
        SessionResponse: {
            /** Session Id */
            session_id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Workspace Path */
            workspace_path: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Accessed
             * Format: date-time
             */
            last_accessed: string;
            /** Status */
            status: string;
            /** Archived */
            archived: boolean;
            /** Ttl Seconds */
            ttl_seconds?: number | null;
            /**
             * Is Indexed
             * @default false
             */
            is_indexed: boolean;
            /**
             * Content Count
             * @default 0
             */
            content_count: number;
        };
        /**
         * UpdateSessionRequest
         * @description Body for PATCH /api/v1/sessions/{session_id} (future use).
         */
        UpdateSessionRequest: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Status */
            status?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_version_api_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_sessions_api_v1_sessions__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_v1_sessions__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_v1_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_session_api_v1_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_workspace_api_v1_workspaces__workspace_id__index_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["IndexWorkspaceRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_index_status_api_v1_workspaces__workspace_id__index_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_content_api_v1_sessions__session_id__content__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_content_api_v1_sessions__session_id__content__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_add_content_api_v1_sessions__session_id__content__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_content_api_v1_sessions__session_id__content__content_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                content_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_content_api_v1_sessions__session_id__content__content_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                content_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_add_content_api_v1_sessions__session_id__content_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchAddContentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchContentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_links_api_v1_content_extract_links_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractLinksRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractedLinksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_logs_api_v1_sessions__session_id__audit_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chat_messages_api_v1_sessions__session_id__chat_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_chat_message_api_v1_sessions__session_id__chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendChatMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageWithStreamUrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_chat_history_api_v1_sessions__session_id__chat_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_chat_response_api_v1_sessions__session_id__chat_stream__message_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_message_api_v1_sessions__session_id__chat__message_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_chat_message_api_v1_sessions__session_id__chat__message_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_chat_history_api_v1_sessions__session_id__chat_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatExportRequest"];
            };
        };
        responses: {
            /** @description Export file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/pdf": unknown;
                    "text/markdown": unknown;
                };
            };
            /** @description Session not found or no messages */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Export generation failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    export_single_message_api_v1_sessions__session_id__chat__message_id__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                message_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatExportRequest"];
            };
        };
        responses: {
            /** @description Export file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/pdf": unknown;
                    "text/markdown": unknown;
                };
            };
            /** @description Invalid message type */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Session, message, or preceding message not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Export generation failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
