/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Version
         * @description Vertical slice: return API version + git sha
         */
        get: operations["get_version_api_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description List sessions with pagination.
         */
        get: operations["list_sessions_api_v1_sessions__get"];
        put?: never;
        /**
         * Create Session
         * @description Create a new research session.
         */
        post: operations["create_session_api_v1_sessions__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description Retrieve a single session by ID.
         */
        get: operations["get_session_api_v1_sessions__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description Delete a session and its workspace directory.
         */
        delete: operations["delete_session_api_v1_sessions__session_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Session
         * @description Update a session's mutable fields (name, description, status).
         */
        patch: operations["update_session_api_v1_sessions__session_id__patch"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Index Workspace
         * @description Trigger indexing for a workspace.
         */
        post: operations["index_workspace_api_v1_workspaces__workspace_id__index_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/index/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Index Status
         * @description Check the indexing status of a workspace.
         */
        get: operations["get_index_status_api_v1_workspaces__workspace_id__index_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/content/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Content
         * @description List all content items for a session with pagination.
         */
        get: operations["list_content_api_v1_sessions__session_id__content__get"];
        put?: never;
        /**
         * Add Content
         * @description Add content to a session.
         *
         *     Supports multiple content types:
         *     - text: Plain text content (source contains the text)
         *     - file_upload: Upload a file (use the file parameter)
         *     - url: Fetch content from URL (source contains the URL)
         *     - git_repo: Clone a git repository (source contains the repo URL)
         */
        post: operations["add_content_api_v1_sessions__session_id__content__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/content/{content_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Content
         * @description Get a single content item by ID.
         */
        get: operations["get_content_api_v1_sessions__session_id__content__content_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Content
         * @description Delete a content item and its storage files.
         */
        delete: operations["delete_content_api_v1_sessions__session_id__content__content_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Audit Logs
         * @description Retrieve audit logs for a session.
         */
        get: operations["get_audit_logs_api_v1_sessions__session_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Health Check
         * @description Health check under the /api/v1 prefix.
         */
        get: operations["api_health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuditLogListResponse
         * @description Paginated list of audit log entries.
         */
        AuditLogListResponse: {
            /** Logs */
            logs: components["schemas"]["AuditLogResponse"][];
            /** Count */
            count: number;
        };
        /**
         * AuditLogResponse
         * @description Single audit log entry returned by the API.
         */
        AuditLogResponse: {
            /** Id */
            id: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Session Id */
            session_id: string;
            /** Action */
            action: string;
            /** Query */
            query?: string | null;
            /** Result Count */
            result_count?: number | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Status */
            status: string;
            /** Error */
            error?: string | null;
            /** Metadata Json */
            metadata_json?: {
                [key: string]: unknown;
            } | null;
        };
        /** Body_add_content_api_v1_sessions__session_id__content__post */
        Body_add_content_api_v1_sessions__session_id__content__post: {
            /**
             * Content Type
             * @description Content type: text, file_upload, url, git_repo
             */
            content_type: string;
            /**
             * Title
             * @description Content title
             */
            title?: string | null;
            /**
             * Source
             * @description Source reference (URL, text)
             */
            source?: string | null;
            /**
             * Metadata
             * @description JSON string of additional metadata
             */
            metadata?: string | null;
            /**
             * File
             * @description File to upload (for file_upload type)
             */
            file?: string | null;
        };
        /**
         * ContentItemResponse
         * @description Single content item returned by the API.
         */
        ContentItemResponse: {
            /** Content Id */
            content_id: string;
            /** Session Id */
            session_id: string;
            /** Content Type */
            content_type: string;
            /** Title */
            title: string;
            /** Source Ref */
            source_ref?: string | null;
            /** Storage Path */
            storage_path?: string | null;
            /** Status */
            status: string;
            /** Error Message */
            error_message?: string | null;
            /** Size Bytes */
            size_bytes?: number | null;
            /** Mime Type */
            mime_type?: string | null;
            /** Metadata Json */
            metadata_json?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ContentListResponse
         * @description Paginated list of content items.
         */
        ContentListResponse: {
            /** Items */
            items: components["schemas"]["ContentItemResponse"][];
            /** Count */
            count: number;
        };
        /**
         * CreateSessionRequest
         * @description Body for POST /api/v1/sessions.
         */
        CreateSessionRequest: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IndexResultResponse
         * @description Response for POST /api/v1/workspaces/{workspace_id}/index.
         */
        IndexResultResponse: {
            /** Workspace Id */
            workspace_id: string;
            /** Success */
            success: boolean;
            /** Status */
            status: string;
            /** Elapsed Seconds */
            elapsed_seconds: number;
            /** Stdout */
            stdout?: string | null;
            /** Stderr */
            stderr?: string | null;
        };
        /**
         * IndexStatusResponse
         * @description Response for GET /api/v1/workspaces/{workspace_id}/index/status.
         */
        IndexStatusResponse: {
            /** Workspace Id */
            workspace_id: string;
            /** Is Indexed */
            is_indexed: boolean;
            /** Status */
            status: string;
            /** Message */
            message: string;
        };
        /**
         * IndexWorkspaceRequest
         * @description Body for POST /api/v1/workspaces/{workspace_id}/index.
         */
        IndexWorkspaceRequest: {
            /**
             * Force
             * @description Force re-index from scratch
             * @default true
             */
            force: boolean;
            /**
             * Timeout
             * @description Custom timeout in seconds (10-600)
             */
            timeout?: number | null;
        };
        /**
         * SessionListResponse
         * @description Paginated list of sessions.
         */
        SessionListResponse: {
            /** Sessions */
            sessions: components["schemas"]["SessionResponse"][];
            /** Count */
            count: number;
        };
        /**
         * SessionResponse
         * @description Single session returned by the API.
         */
        SessionResponse: {
            /** Session Id */
            session_id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Workspace Path */
            workspace_path: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Accessed
             * Format: date-time
             */
            last_accessed: string;
            /** Status */
            status: string;
            /** Archived */
            archived: boolean;
            /** Ttl Seconds */
            ttl_seconds?: number | null;
            /**
             * Is Indexed
             * @default false
             */
            is_indexed: boolean;
            /**
             * Content Count
             * @default 0
             */
            content_count: number;
        };
        /**
         * UpdateSessionRequest
         * @description Body for PATCH /api/v1/sessions/{session_id} (future use).
         */
        UpdateSessionRequest: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Status */
            status?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_version_api_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_sessions_api_v1_sessions__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_v1_sessions__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_v1_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_session_api_v1_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_workspace_api_v1_workspaces__workspace_id__index_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["IndexWorkspaceRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_index_status_api_v1_workspaces__workspace_id__index_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_content_api_v1_sessions__session_id__content__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_content_api_v1_sessions__session_id__content__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_add_content_api_v1_sessions__session_id__content__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_content_api_v1_sessions__session_id__content__content_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                content_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_content_api_v1_sessions__session_id__content__content_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                content_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_logs_api_v1_sessions__session_id__audit_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
